# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wp0moCsLXqqpOvb90TLLvvF-t4M4D9gS
"""

# Concatiute two variable of fisrname & last narne

first_name= "Naved "
last_name = "Alam"
print(first_name + last_name)

# Create a string variable of yow fisrname and lastname slice a string using indexing so it print your fisrtname

full_name = first_name + last_name

print(full_name[0:5])

# Create a with difrent states of india

indian_states= ["Maharashtra","Delhi", "Punjab","Haryana","Uttarakhand","UP","MP","Gujrat", "Bengal"]

# Print these diffrent states of india

for IS in indian_states:
  print(IS)

